version: "3.9"
services:
  api:
    container_name: back
    build: "./app"
    depends_on: 
      - postgres

  web:
    container_name: front
    build: "./web"
    depends_on: 
      - api

  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
        - "5432:5432"

  proxy:
    container_name: proxy
    build: "./proxy"
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./proxy:/app